trigger: none

pool: Pra_pipe

stages:
  - stage: Terraforminstaller
    displayName: Teraform tool installer
    jobs:
      - job: Terraforminstaller
        displayName: Terraform tool installer
        steps:
        - task: TerraformInstaller@1
          displayName: Terraform installer 
          inputs:
            terraformVersion: 'latest'
            
  - stage: Terraforminitplanandtfsec
    displayName: Terraform init, plan and tfsec
    jobs:
      - job: Terrforminitandplan
        displayName: Terraform init
        steps:
        - task: TerraformTaskV4@4
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environments'
            backendServiceArm: 'Websure_Service_Connection'
            backendAzureRmResourceGroupName: 'prashant_rg'
            backendAzureRmStorageAccountName: 'prastoragehai'
            backendAzureRmContainerName: 'mypracontainer'
            backendAzureRmKey: 'terraform.tfstate'
        
        - task: TerraformTaskV4@4
          displayName: terraform plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environments'
            environmentServiceNameAzureRM: 'Websure_Service_Connection'

  - stage: ManualValidationandterrformapply
    displayName: Manual Validation and terrform apply  
    jobs:
      - job: Manualvalidation
        displayName: Manualvalidation
        pool: server
        steps:
        - task: ManualValidation@1
          displayName: manual validation
          inputs:
            notifyUsers: 'prashantgi1995@gmail.com'
            approvers: 'prashantgi1995@gmail.com'

      - job: Terraformapply
        displayName: Terraform apply
        steps:
        - task: TerraformTaskV4@4
          displayName: terraform plan
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environments'
            environmentServiceNameAzureRM: 'Websure_Service_Connection'
        